@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: : application/json

{
    "name": "Luigi Bertoli Menezes",
    "email": "luigi.menezes@v4company.com",
    "password": "123456s"
}

###

