@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: : application/json

{
    "name": "Luigi Bertoli Menezes",
    "email": "luigi.menezes@v4company.com",
    "password": "123456s"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: : application/json

{
    "email": "luigi.menezes@v4company.com",
    "password": "123456s"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}