services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432 # Redirecionando a porta 5432 do postgres de dentro do container para a porta 5432 do host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
     